### ISSUE TITLE
Add --max-width argument to adapt automatically the size of the preview.

### ISSUE THREAD

**Issue by JohannesRgnr** [AnirudhG07/rich-preview.yazi#2]
Thank you for the plugin.
A small suggestion, to adapt the width of the preview to the side of the panel:
In init.lua, in args, add:
```
"--max-width",
tostring(self.area.w),
```

Tested with markdown files and Jupyter notebooks, seems to work well.

**Comment by AnirudhG07** [comment]
Oh alright. For me it was working even without it. Sure maybe it would differ for every person and needs to be enforced.
Would you like to make a PR to add it?

**Comment by AnirudhG07** [comment]
The PR #4  should resolve this issue. Thanks!
